name: chatgamesWhosvon
version: '1.0'
main: com.whosvon.chatgames.chatgames.ChatgamesWhosvon
api-version: '1.20'
load: STARTUP
commands:
  chatgame:
    description: Start or reload ChatgamesWhosvon
    usage: /chatgame <start|reload|answer>
